# Generated by Django 5.0.6 on 2024-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.CharField(max_length=20, unique=True)),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=50)),
                ('location_description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('food_items', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('schedule', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
